CREATE INDEX ON :ptal_aj (id);
CREATE INDEX ON :ptal_aj (ajlx);
CREATE INDEX ON :ptal_aj (ay);
CREATE INDEX ON :ptal_aj (ys);
;
CREATE INDEX ON :ptal_ajjc (id);
CREATE INDEX ON :ptal_ajjc (name);
CREATE INDEX ON :ptal_ajjc (ah);
CREATE INDEX ON :ptal_ajjc (ay);
CREATE INDEX ON :ptal_ajjc (ys);
;
CREATE INDEX ON :ptal_ws (id);
CREATE INDEX ON :ptal_ws (title);
CREATE INDEX ON :ptal_ws (ay);
CREATE INDEX ON :ptal_ws (ys);
CREATE INDEX ON :ptal_ws (ah);
;
CREATE INDEX ON :ptal_yssl (id);
CREATE INDEX ON :ptal_yssl (keyword);
;
CREATE INDEX ON :flys (id);
CREATE INDEX ON :flys (name);
;
CREATE INDEX ON :law (id);
CREATE INDEX ON :law (name);
CREATE INDEX ON :law (indexName);
;
CREATE INDEX ON :ft (id);
CREATE INDEX ON :ft (name);
CREATE INDEX ON :ft (indexName);
;
CREATE INDEX ON :lawyer (id);
CREATE INDEX ON :lawyer (name);
;
;
CREATE INDEX ON :ls (id);
CREATE INDEX ON :ls (name);
;
CREATE INDEX ON :fg (id);
CREATE INDEX ON :fg (name);
CREATE INDEX ON :fg (fy);
;
CREATE INDEX ON :fy (id);
CREATE INDEX ON :fy (name);
;
CREATE INDEX ON :qwal (id);
CREATE INDEX ON :qwal (title);
CREATE INDEX ON :qwal (ay);
CREATE INDEX ON :qwal (ys);
;
CREATE INDEX ON :qwal_yssl (id);
CREATE INDEX ON :qwal_yssl (ovalue);
;
CREATE INDEX ON :ay (id);
CREATE INDEX ON :ay (name);


